############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Download"
url = "#downloads-section"
weight = 2

[[main]]
name = "Products"
url = "/Products"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4
