baseURL = 'https://www.aurozeon.com/'
languageCode = 'en-us'
title = 'AuroZeon'

theme = 'aurozeon'

# Allow raw HTML in markdown files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Suppress specific warnings
ignoreLogs = ['warning-goldmark-raw-html']


